### ISSUE TITLE
pypi page still links to http://berkeleyanalytics.com/bottleneck

### ISSUE THREAD

**Issue by jhamman** [pydata/bottleneck#173]
It looks like you've moved bottleneck's documentation to github.io (87ae3e397ca4a78f02a530058be055728d47418d). However, the link on the [pypi](https://pypi.python.org/pypi/Bottleneck#Where) still links to http://berkeleyanalytics.com/bottleneck. Probably could use an update.

**Comment by kwgoodman** [comment]
pypi used to have an edit button (to edit PKG-INFO). Seems to be gone now. I guess I could try re-uploading the release. A bit scared though.

**Comment by qwhelan** [comment]
This is resolved by the release of 1.3.0. The documentation url on PyPI now points to https://bottleneck.readthedocs.io
