### ISSUE TITLE
Py2 Support

### ISSUE THREAD

**Issue by staylor-c7ks7s** [pydata/bottleneck#208]
Can we open discussion on a py2 fix. Currently install_requires has numpy version open. This version 1.2.1 is stated to support py2. numpy 1.17 drops support for py2. Recent install are trying to grab numpy 1.17.rcX

**Comment by orrery** [comment]
this would be great

**Comment by chargrnv** [comment]
Numpy 1.17 was released today, but yet this still tries to install the rc2?

```
      File "/tmp/easy_install-vgXOEV/numpy-1.17.0rc2/setup.py", line 31, in <module>
        from bottleneck.src.template import make_c_files
    RuntimeError: Python version >= 3.5 required.
```

If I put "numpy" in a requirements.txt - it installs the 1.16 version (because pip checks python version requirements?) but when done through setup.py it seems to grab the rc candidate still.

**Comment by qwhelan** [comment]
@staylor-c7ks7s Could you try with current `bottleneck` master? I've recently taken over maintainership and am inventorying release blockers for `1.3.0`

**Comment by qwhelan** [comment]
I believe the build changes in 1.3.0 should resolve this issue, but please feel free to re-open if not.

Given the widespread dropping of Py2 support, I expect this to be the last major release supporting Python 2.
