### ISSUE TITLE
Future of bottleneck

### ISSUE THREAD

**Issue by kwgoodman** [pydata/bottleneck#209]
Due to health problems, I can no longer maintain bottleneck. I hope that bottleneck is forked and a dominant fork emerges. Thanks to all who have reported issues and made PRs or just stopped by to say hello.

**Comment by aterrel** [comment]
Howdy! Can we transfer ownership of the org to Chris Whelan has offered to manage it. I can help with the administration parts

https://groups.google.com/forum/m/#!topic/pydata/RsflopkiLw4

**Comment by kwgoodman** [comment]
That is a great offer!

I cannot transfer directly to pydata because I do not have write privileges. But I can transfer to you @aterrel and then you can transfer to pydata.

Thank you @qwhelan for taking this on!

**Comment by aterrel** [comment]
Okay feel free to transfer to me and I'll make the next hop happen.

**Comment by qwhelan** [comment]
@kwgoodman Thank you for all your work on bottleneck! It's been an invaluable tool for me over the years and I'm excited to help make it an even more core part of the ecosystem.

@aterrel Thank you for helping with the administration parts!

**Comment by aterrel** [comment]
The transfer is complete. I’ll create an admin team. Who all should be on it?

**Comment by qwhelan** [comment]
@aterrel I haven't had anyone express interest in co-maintaining as of yet. I would say myself, @kwgoodman if he'd like to be, and yourself (or anyone with broad pydata admin rights).

Just to repeat my offer for anyone stopping by this thread: if you would like to be a co-maintainer with me, please mention that in this thread by Friday. I want to keep that to at most one other person.

If you are interested in being a co-maintainer significantly after this week, please be an active contributor and we can discuss after I have a few bottleneck releases under my belt.
