### ISSUE TITLE
Memory leak in 1.3.0

### ISSUE THREAD

**Issue by jsmodic** [pydata/bottleneck#276]
We upgraded to 1.3.0 but had to rollback to 1.2.1 because there's a memory leak. It was pretty easy to observe as all our data processing containers would go consistently OOM with this release after about a half hour vs having tightly constrained memory in the previous release.

It's hard to track down exactly where as the code in question is using a mix of 
nansum,nanargmax,nanargmin,nanmedian,nansum,nanmean,nanmin,nanmax,nanvar,nanmedian.

But I want to make sure this gets filed as there is something lurking here that could bite others as well.

**Comment by qwhelan** [comment]
Thanks for reporting - could you provide an environment description?

**Comment by jsmodic** [comment]
Oh yeah, sure:

Ubuntu 16.04.6 LTS
Python 3.6.8
numpy==1.16.0
Bottleneck==1.3.0

**Comment by qwhelan** [comment]
Thanks! I'm about to hop on a flight, but I had been meaning to create some memory benchmarks in `asv` to detect leaks. Might take a bit of experimentation, but a correct benchmark would be able to bisect the bad commit with `asv find`.

Unfortunately, a good chunk of `1.3.0` development prior to my taking over never built correctly, so may prove tricky to track down if suspect commit is from before August.

**Comment by qwhelan** [comment]
@jsmodic If you're able to try installing from source, I'd appreciate it if you could check whether the fix in #278 fully resolves the issue for your workload.

**Comment by qwhelan** [comment]
Bottleneck 1.3.1 has been uploaded to PyPI - conda-forge packages should be available soon.

**Comment by jsmodic** [comment]
Great! I won't be able to test it until Monday but the results look promising.

**Comment by jsmodic** [comment]
@qwhelan 1.3.1 looks good. thanks!

**Comment by qwhelan** [comment]
Thanks again for reporting!
