### ISSUE TITLE
[BUG] Module "hypothesis" not listed as dependency

### ISSUE THREAD

**Issue by aulemahal** [pydata/bottleneck#352]
**Describe the bug**
The `hypothesis` is used in `bottleneck.test.util`, which gets imported in `bottleneck/__init__.py`. As the package is not listed in the `requires` field of `setup.py`, importing bottleneck fails.

**To Reproduce**
In a new environment, install bottleneck from source (`pip install -e .`). Open an interpreter and try `import bottleneck`, this will fail with:
```
In [1]: import bottleneck                                                                                             
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-baae57b98b2a> in <module>
----> 1 import bottleneck

~/Python/bottleneck/bottleneck/__init__.py in <module>
     43 from bottleneck.benchmark.bench import bench
     44 from bottleneck.benchmark.bench_detailed import bench_detailed
---> 45 from bottleneck.tests.util import get_functions
     46 from ._pytesttester import PytestTester
     47 from ._version import get_versions  # noqa: E402

~/Python/bottleneck/bottleneck/tests/util.py in <module>
      2 
      3 import numpy as np
----> 4 from hypothesis.extra.numpy import array_shapes
      5 from hypothesis.extra.numpy import arrays as hy_arrays
      6 from hypothesis.extra.numpy import floating_dtypes, integer_dtypes

ModuleNotFoundError: No module named 'hypothesis'
```
Python : 3.8.3
bottleneck : master (1.4.0.dev0+78.g7c685ae)

**Expected behavior**
No `ModuleNotFoundError`

**Additional context**
Installing `hypothesis` (I did `conda install hypothesis`) fixes the problem.

**Comment by qwhelan** [comment]
Thanks for reporting and apologies for the delay! Should be fixed now in `master`
