### ISSUE TITLE
ImportError: bottleneck modules failed to import, likely due to a mismatch in NumPy versions.

### ISSUE THREAD

**Issue by SpringW1nd** [pydata/bottleneck#380]
I tried to build bottleneck from source. I successfully run the setup.py:
**python ./setup.py install**
and the result shows:
**Installed /usr/local/lib/python3.7/dist-packages/Bottleneck-1.4.0.dev0+117.gf2bc792-py3.7-linux-x86_64.egg
Processing dependencies for Bottleneck==1.4.0.dev0+117.gf2bc792
Searching for numpy==1.19.5
Best match: numpy 1.19.5
Adding numpy 1.19.5 to easy-install.pth file
Installing f2py script to /usr/local/bin
Installing f2py3 script to /usr/local/bin
Installing f2py3.7 script to /usr/local/bin

Using /usr/local/lib/python3.7/dist-packages
Finished processing dependencies for Bottleneck==1.4.0.dev0+117.gf2bc792
**
However, when I tried to import bottleneck , the error occured:
**>>> import numpy as np
>>> a = np.array([1, 2, np.nan, 4, 5])
>>> import bottleneck as bn
Traceback (most recent call last):
  File "/home/wen/code/bottleneck/bottleneck/__init__.py", line 3, in <module>
    from .move import (
ModuleNotFoundError: No module named 'bottleneck.move'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wen/code/bottleneck/bottleneck/__init__.py", line 35, in <module>
    "bottleneck modules failed to import, likely due to a "
ImportError: bottleneck modules failed to import, likely due to a mismatch in NumPy versions. Either upgrade numpy to 1.16+ or install with:
	pip install --no-build-isolation --no-cache-dir bottleneck**
I tried to reinstall bottleneck through pip, but it still did not work.
My numpy's version is 1.19.5, I tried to change the version of numpy as well. It still did not work.

**Comment by rdbisme** [comment]
Hello, installing the current `master` doing `pip install -e .`  in the repo root should install bottleneck as expected. I'll close the issue, but feel free to reopen if the issue persists.
