### ISSUE TITLE
Issue ERROR: Could not build wheels for bottleneck which use PEP 517 while installing a repo from GitHub

### ISSUE THREAD

**Issue by Aliktk** [pydata/bottleneck#384]
Hello everyone I am installing a repo which is link here: [Link](https://github.com/renato145/RpSalWeaklyDet)
I created an environment in `Conda `with `Python 3.6`. While installing the repo I am getting the issue while this issue didn't occurred when I installed on Linux many time.
I am confused why its stuck at end of all installation of that repo requirements. 
I am using window 10:
installed all Microsoft Build tools and other pip upgradation and many more solution which are there on google and github.
Please help 
 
`  Created wheel for rpsalweaklydet: filename=rpsalweaklydet-0.0.1-py3-none-any.whl size=31181 sha256=4fe90b45a1b512a33e61e9906c1f5dce7636995b00bcf4e43e9d81eb4efac2cf
  Stored in directory: C:\Users\Nawaz\AppData\Local\Temp\pip-ephem-wheel-cache-52sjedgq\wheels\9d\55\49\63427c620b39df590b6b7e116836a11d51e2d47bb2bae80609
  Building wheel for bottleneck (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Nawaz\anaconda3\envs\chest-detect\python.exe' 'C:\Users\Nawaz\anaconda3\envs\chest-detect\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\Nawaz\AppData\Local\Temp\tmptvtnfi2y'
       cwd: C:\Users\Nawaz\AppData\Local\Temp\pip-install-2a9e3311\bottleneck_28b15b21a1184a65b0d0541646bf9916
  Complete output (51 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\bottleneck
  copying bottleneck\_pytesttester.py -> build\lib.win-amd64-3.6\bottleneck
  copying bottleneck\_version.py -> build\lib.win-amd64-3.6\bottleneck
  copying bottleneck\__init__.py -> build\lib.win-amd64-3.6\bottleneck
  creating build\lib.win-amd64-3.6\bottleneck\benchmark
  copying bottleneck\benchmark\autotimeit.py -> build\lib.win-amd64-3.6\bottleneck\benchmark
  copying bottleneck\benchmark\bench.py -> build\lib.win-amd64-3.6\bottleneck\benchmark
  copying bottleneck\benchmark\bench_detailed.py -> build\lib.win-amd64-3.6\bottleneck\benchmark
  copying bottleneck\benchmark\__init__.py -> build\lib.win-amd64-3.6\bottleneck\benchmark
  creating build\lib.win-amd64-3.6\bottleneck\slow
  copying bottleneck\slow\move.py -> build\lib.win-amd64-3.6\bottleneck\slow
  copying bottleneck\slow\nonreduce.py -> build\lib.win-amd64-3.6\bottleneck\slow
  copying bottleneck\slow\nonreduce_axis.py -> build\lib.win-amd64-3.6\bottleneck\slow
  copying bottleneck\slow\reduce.py -> build\lib.win-amd64-3.6\bottleneck\slow
  copying bottleneck\slow\__init__.py -> build\lib.win-amd64-3.6\bottleneck\slow
  creating build\lib.win-amd64-3.6\bottleneck\src
  copying bottleneck\src\bn_config.py -> build\lib.win-amd64-3.6\bottleneck\src
  copying bottleneck\src\bn_template.py -> build\lib.win-amd64-3.6\bottleneck\src
  copying bottleneck\src\__init__.py -> build\lib.win-amd64-3.6\bottleneck\src
  creating build\lib.win-amd64-3.6\bottleneck\tests
  copying bottleneck\tests\input_modification_test.py -> build\lib.win-amd64-3.6\bottleneck\tests
  copying bottleneck\tests\list_input_test.py -> build\lib.win-amd64-3.6\bottleneck\tests
  copying bottleneck\tests\memory_test.py -> build\lib.win-amd64-3.6\bottleneck\tests
  copying bottleneck\tests\move_test.py -> build\lib.win-amd64-3.6\bottleneck\tests
  copying bottleneck\tests\nonreduce_axis_test.py -> build\lib.win-amd64-3.6\bottleneck\tests
  copying bottleneck\tests\nonreduce_test.py -> build\lib.win-amd64-3.6\bottleneck\tests
  copying bottleneck\tests\reduce_test.py -> build\lib.win-amd64-3.6\bottleneck\tests
  copying bottleneck\tests\scalar_input_test.py -> build\lib.win-amd64-3.6\bottleneck\tests
  copying bottleneck\tests\util.py -> build\lib.win-amd64-3.6\bottleneck\tests
  copying bottleneck\tests\__init__.py -> build\lib.win-amd64-3.6\bottleneck\tests
  UPDATING build\lib.win-amd64-3.6\bottleneck/_version.py
  set build\lib.win-amd64-3.6\bottleneck/_version.py to '1.3.2'
  running build_ext
  running config
  compiling '_configtest.c':

  int __attribute__((optimize("O3"))) have_attribute_optimize_opt_3(void*);

  int main(void)
  {
      return 0;
  }

  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for bottleneck
Successfully built rpsalweaklydet
Failed to build bottleneck
ERROR: Could not build wheels for bottleneck which use PEP 517 and cannot be installed directly`

**Comment by rdbisme** [comment]
Hello, pre-compiled wheels have been pushed and this should be fixed. Anyway for the issue here, in order to compile bottleneck from sdist you need to have an available compiler.
