### ISSUE TITLE
I think no Bug - just a unexperienced elderly user... having Vers. 1.2.1

### ISSUE THREAD

**Issue by JStefanRaspi** [pydata/bottleneck#416]
Having no Luck to find a way to upgrade to 1.3.1 what pandas ask for. Pls let me know how to do...
All that on a RPI 4 / Bullseye / Python 3.9 / 

"/home/pi/.local/lib/python3.9/site-packages/pandas/compat/_optional.py:161: UserWarning: Pandas requires version '1.3.1' or newer of 'bottleneck' (version '1.2.1' currently installed).
  warnings.warn(msg, UserWarning)"

Thx a lot
Stefan

**Comment by JStefanRaspi** [comment]
$ pip3 install bottleneck 1.3.1 no cache
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: bottleneck in /usr/lib/python3/dist-packages (1.2.1)
ERROR: Could not find a version that satisfies the requirement 1.3.1
ERROR: No matching distribution found for 1.3.1

Where is my mistake?

**Comment by rdbisme** [comment]
Try just to update to the latest version: 
`pip install -U bottleneck`

Also I suggest to do this on a virtualenv (and not the system python as you are doing), to avoid disrupting your system environment. 

```
python -m venv my_env
source my_env/bin/activate
python -m pip install bottleneck
```

try to use a single virtualev per project.

**Comment by JStefanRaspi** [comment]
**pip3 install -U bottleneck**

did it.. works now without error. thank you sir
Stefan
