### ISSUE TITLE
[BUG]Can't install on MacOSX 14.1.1

### ISSUE THREAD

**Issue by burryxie** [pydata/bottleneck#444]
**Describe the bug**
MacOS Sonoma 14.1.1. Python 3.11.7. Trying to install this package and got an error `ERROR: Could not build wheels for bottleneck, which is required to install pyproject.toml-based projects`. 
So I tried to download the .whl file from [here](https://pypi.org/project/Bottleneck/#files) and install like `pip install Bottleneck-1.3.7-cp311-cp311-macosx_10_9_x86_64.whl ` but still get an error: `ERROR: Bottleneck-1.3.7-cp311-cp311-macosx_10_9_x86_64.whl is not a supported wheel on this platform.`
Can anyone help get this out?

**To Reproduce**
pip version `pip 24.0 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)`

**Expected behavior**
install the package smoothly

**Additional context**
Null

**Comment by rdbisme** [comment]
Is your Mac `x86_64` based? Or it's on Apple Silicon?

**Comment by burryxie** [comment]
@rdbisme Apple Silicon M2

**Comment by rdbisme** [comment]
Duplicate: https://github.com/pydata/bottleneck/issues/394
