### ISSUE TITLE
I am trying to install opencage on pycharm but it showing this issue

### ISSUE THREAD

**Issue by kripan0** [pydata/bottleneck#465]
(venv) C:\Users\user\PycharmProjects\track no>pip install opencage
C:\Users\user\PycharmProjects\track no\venv\Scripts\pip-script.py:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
Collecting opencage
  Using cached https://files.pythonhosted.org/packages/8e/91/012b9f0561a56aef20a748ca4ac18358165aff02e5ce462a9a3a7c4fda67/opencage-3.0.2-py3-none-any.whl
Requirement already satisfied: tqdm>=4.66.4 in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from opencage) (4.67.0)
Requirement already satisfied: certifi>=2024.07.04 in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from opencage) (2024.8.30)
Collecting aiohttp>=3.10.5 (from opencage)
  Using cached https://files.pythonhosted.org/packages/17/7e/16e57e6cf20eb62481a2f9ce8674328407187950ccc602ad07c685279141/aiohttp-3.10.10.tar.gz
  Missing build time requirements in pyproject.toml for aiohttp>=3.10.5 from https://files.pythonhosted.org/packages/17/7e/16e57e6cf20eb62481a2f9ce8674328407187950ccc602ad07c685279141/aioht
tp-3.10.10.tar.gz#sha256=0631dd7c9f0822cc61c88586ca76d5b5ada26538097d0f1df510b082bad3411a (from opencage): 'wheel'.
  This version of pip does not implement PEP 517 so it cannot build a wheel without 'setuptools' and 'wheel'.
  Installing build dependencies ... done
Requirement already satisfied: backoff>=2.2.1 in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from opencage) (2.2.1)
Requirement already satisfied: Requests>=2.31.0 in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from opencage) (2.32.3)
Requirement already satisfied: colorama; platform_system == "Windows" in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from tqdm>=4.66.4->opencage) (0.4.6)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from aiohttp>=3.10.5->opencage) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from aiohttp>=3.10.5->opencage) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from aiohttp>=3.10.5->opencage) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from aiohttp>=3.10.5->opencage) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from aiohttp>=3.10.5->opencage) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from aiohttp>=3.10.5->opencage) (1.15.2)
Requirement already satisfied: async-timeout<5.0,>=4.0 in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from aiohttp>=3.10.5->opencage) (4.0.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from Requests>=2.31.0->opencage) (3.4.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from Requests>=2.31.0->opencage) (2.2.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from Requests>=2.31.0->opencage) (3.10)
Requirement already satisfied: typing-extensions>=4.1.0; python_version < "3.11" in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from multidict<7.0,>=4.5->aiohttp>=3.10.5-
>opencage) (4.12.2)
Requirement already satisfied: propcache>=0.2.0 in c:\users\user\pycharmprojects\track no\venv\lib\site-packages (from yarl<2.0,>=1.12.0->aiohttp>=3.10.5->opencage) (0.2.0)
Building wheels for collected packages: aiohttp
  Running setup.py bdist_wheel for aiohttp ... error
  Complete output from command "C:\Users\user\PycharmProjects\track no\venv\Scripts\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-insta
ll-k6yrd8d5\\aiohttp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\user
\AppData\Local\Temp\pip-wheel-klhdsrya --python-tag cp38:
  *********************
  * Accelerated build *
  *********************
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win32-cpython-38\aiohttp
  copying aiohttp\abc.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\base_protocol.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\client.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\client_exceptions.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\client_proto.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\client_reqrep.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\client_ws.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\compression_utils.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\connector.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\cookiejar.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\formdata.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\hdrs.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\helpers.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\http.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\http_exceptions.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\http_parser.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\http_websocket.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\http_writer.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\log.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\multipart.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\payload.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\payload_streamer.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\pytest_plugin.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\resolver.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\streams.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\tcp_helpers.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\test_utils.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\tracing.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\typedefs.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\web.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\web_app.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\web_exceptions.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\web_fileresponse.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\web_log.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\web_middlewares.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\web_protocol.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\web_request.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\web_response.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\web_routedef.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\web_runner.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\web_server.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\web_urldispatcher.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\web_ws.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\worker.py -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\__init__.py -> build\lib.win32-cpython-38\aiohttp
  running egg_info
  writing aiohttp.egg-info\PKG-INFO
  writing dependency_links to aiohttp.egg-info\dependency_links.txt
  writing requirements to aiohttp.egg-info\requires.txt
  writing top-level names to aiohttp.egg-info\top_level.txt
  reading manifest file 'aiohttp.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'aiohttp' anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching '*.lib' found anywhere in distribution
  warning: no previously-included files matching '*.dll' found anywhere in distribution
  warning: no previously-included files matching '*.a' found anywhere in distribution
  warning: no previously-included files matching '*.obj' found anywhere in distribution
  warning: no previously-included files found matching 'aiohttp\*.html'
  no previously-included directories found matching 'docs\_build'
  adding license file 'LICENSE.txt'
  writing manifest file 'aiohttp.egg-info\SOURCES.txt'
  copying aiohttp\_cparser.pxd -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\_find_header.pxd -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\_headers.pxi -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\_helpers.pyi -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\_helpers.pyx -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\_http_parser.pyx -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\_http_writer.pyx -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\_websocket.pyx -> build\lib.win32-cpython-38\aiohttp
  copying aiohttp\py.typed -> build\lib.win32-cpython-38\aiohttp
  creating build\lib.win32-cpython-38\aiohttp\.hash
  copying aiohttp\.hash\_cparser.pxd.hash -> build\lib.win32-cpython-38\aiohttp\.hash
  copying aiohttp\.hash\_find_header.pxd.hash -> build\lib.win32-cpython-38\aiohttp\.hash
  copying aiohttp\.hash\_helpers.pyi.hash -> build\lib.win32-cpython-38\aiohttp\.hash
  copying aiohttp\.hash\_helpers.pyx.hash -> build\lib.win32-cpython-38\aiohttp\.hash
  copying aiohttp\.hash\_http_parser.pyx.hash -> build\lib.win32-cpython-38\aiohttp\.hash
  copying aiohttp\.hash\_http_writer.pyx.hash -> build\lib.win32-cpython-38\aiohttp\.hash
  copying aiohttp\.hash\_websocket.pyx.hash -> build\lib.win32-cpython-38\aiohttp\.hash
  copying aiohttp\.hash\hdrs.py.hash -> build\lib.win32-cpython-38\aiohttp\.hash
  running build_ext
  building 'aiohttp._websocket' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

  ----------------------------------------
  Failed building wheel for aiohttp
  Running setup.py clean for aiohttp
Failed to build aiohttp
Installing collected packages: aiohttp, opencage
  Running setup.py install for aiohttp ... error
    Complete output from command "C:\Users\user\PycharmProjects\track no\venv\Scripts\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-ins
tall-k6yrd8d5\\aiohttp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\
user\AppData\Local\Temp\pip-record-xc8zvgv5\install-record.txt --single-version-externally-managed --compile --install-headers "C:\Users\user\PycharmProjects\track no\venv\include\site\pyth
on3.8\aiohttp":
    *********************
    * Accelerated build *
    *********************
    running install
    C:\Users\user\AppData\Local\Temp\pip-build-env-4nd15rbp\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************

    !!
      self.initialize_options()
    running build
    running build_py
    creating build\lib.win32-cpython-38\aiohttp
    copying aiohttp\abc.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\base_protocol.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\client.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\client_exceptions.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\client_proto.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\client_reqrep.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\client_ws.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\compression_utils.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\connector.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\cookiejar.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\formdata.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\hdrs.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\helpers.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\http.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\http_exceptions.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\http_parser.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\http_websocket.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\http_writer.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\log.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\multipart.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\payload.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\payload_streamer.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\pytest_plugin.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\resolver.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\streams.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\tcp_helpers.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\test_utils.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\tracing.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\typedefs.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\web.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\web_app.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\web_exceptions.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\web_fileresponse.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\web_log.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\web_middlewares.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\web_protocol.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\web_request.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\web_response.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\web_routedef.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\web_runner.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\web_server.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\web_urldispatcher.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\web_ws.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\worker.py -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\__init__.py -> build\lib.win32-cpython-38\aiohttp
    running egg_info
    writing aiohttp.egg-info\PKG-INFO
    writing dependency_links to aiohttp.egg-info\dependency_links.txt
    writing requirements to aiohttp.egg-info\requires.txt
    writing top-level names to aiohttp.egg-info\top_level.txt
    reading manifest file 'aiohttp.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'aiohttp' anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.lib' found anywhere in distribution
    warning: no previously-included files matching '*.dll' found anywhere in distribution
    warning: no previously-included files matching '*.a' found anywhere in distribution
    warning: no previously-included files matching '*.obj' found anywhere in distribution
    warning: no previously-included files found matching 'aiohttp\*.html'
    no previously-included directories found matching 'docs\_build'
    adding license file 'LICENSE.txt'
    writing manifest file 'aiohttp.egg-info\SOURCES.txt'
    copying aiohttp\_cparser.pxd -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\_find_header.pxd -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\_headers.pxi -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\_helpers.pyi -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\_helpers.pyx -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\_http_parser.pyx -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\_http_writer.pyx -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\_websocket.pyx -> build\lib.win32-cpython-38\aiohttp
    copying aiohttp\py.typed -> build\lib.win32-cpython-38\aiohttp
    creating build\lib.win32-cpython-38\aiohttp\.hash
    copying aiohttp\.hash\_cparser.pxd.hash -> build\lib.win32-cpython-38\aiohttp\.hash
    copying aiohttp\.hash\_find_header.pxd.hash -> build\lib.win32-cpython-38\aiohttp\.hash
    copying aiohttp\.hash\_helpers.pyi.hash -> build\lib.win32-cpython-38\aiohttp\.hash
    copying aiohttp\.hash\_helpers.pyx.hash -> build\lib.win32-cpython-38\aiohttp\.hash
    copying aiohttp\.hash\_http_parser.pyx.hash -> build\lib.win32-cpython-38\aiohttp\.hash
    copying aiohttp\.hash\_http_writer.pyx.hash -> build\lib.win32-cpython-38\aiohttp\.hash
    copying aiohttp\.hash\_websocket.pyx.hash -> build\lib.win32-cpython-38\aiohttp\.hash
    copying aiohttp\.hash\hdrs.py.hash -> build\lib.win32-cpython-38\aiohttp\.hash
    running build_ext
    building 'aiohttp._websocket' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

    ----------------------------------------
Command ""C:\Users\user\PycharmProjects\track no\venv\Scripts\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-k6yrd8d5\\aiohttp\\
setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\
pip-record-xc8zvgv5\install-record.txt --single-version-externally-managed --compile --install-headers "C:\Users\user\PycharmProjects\track no\venv\include\site\python3.8\aiohttp"" failed w
ith error code 1 in C:\Users\user\AppData\Local\Temp\pip-install-k6yrd8d5\aiohttp\
You are using pip version 10.0.1, however version 24.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by rdbisme** [comment]
Hello, for whatever reason, your Windows machine is trying to build from sources `aiohttp._websocket` and you don't have the compiler installed on your machine. 

The shown error tells you how to fix the contingent problem. 

This seems unrelated to `bottleneck.` We ship pre-build wheel for Python 3.9+, we have deprecated Python 3.8 which seems you're using. 

Python 3.8 is EOL, so I suggest to update your Python distribution.
